# Generated by Django 3.0.6 on 2020-05-16 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200516_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bloger_name',
            new_name='bloger_about',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogger_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 12, 54, 11, 870003)),
        ),
    ]
