# Generated by Django 3.0.6 on 2020-05-16 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200516_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 16, 12, 56, 37, 867075)),
        ),
    ]
